@api = http://localhost:5000


###Get all videos
GET {{api}}/videos

###Get single videos
GET {{api}}/video/1

###Send Video Request
POST {{api}}/video
Content-Type: application/json

{
    "url":"https://www.youtube.com/watch?v=y1ZqhQySFKw",
    "title":"Any Title",
    "description":"Any Description"
}

###Remove video
DELETE  {{api}}/video/1

###Update video
PUT  {{api}}/video/1