@api = http://localhost:5000


###Get all videos
GET {{api}}/videos

###Get single videos
GET {{api}}/video/61fa2c79b802ed554e757eb4

###Send Video Request
POST {{api}}/video
Content-Type: application/json

{
    "url":"https://www.youtube.com/watch?v=y1ZqhQySFKw",
    "title":"Any Title",
    "description":"Any Description"
}

###Remove video
DELETE  {{api}}/video/61fa2c79b802ed554e757eb1

###Update video
PUT  {{api}}/video/61fa3636c97a1b34112f9b8d
Content-Type: application/json

{
    "title":"Updated Title"
}